{% set name = "mcstas-readout-master" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/g5t/mcstas-readout-master/archive/v{{ version }}.tar.gz
  sha256: 64dea61e66f2fa71efa4fb32caeb81f6640028bc26600510aceb861352e81572

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('mcstas-readout-master') }}
  ignore_run_exports_from:
    - python

requirements:
  build:
    - python
    - cmake >=3.30
    - make  # [not win]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - highfive
    - catch2
  run:
    - hdf5

test:
  commands:
    - readout-config --help
    - readout-config --version
    - readout-replay --help
    - test -f ${PREFIX}/include/Readout.h  # [not win]
    - if not exist %PREFIX%\\include\\Readout.h exit 1  # [win]
    - cmake-package-check Readout --targets Readout
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/g5t/mcstas-readout-master
  summary: 'McStas Readout Master for ESS detectors'
  description: |
    Provides McStas components to mimic different detector-types supported
    by the ESS Readout Master and Event Formation Unit, as well as the
    necessary C++ shared library to enable sending packet-ized data to
    an external EFU at McStas simulation runtime.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/g5t/mcstas-readout-master
  dev_url: https://github.com/g5t/mcstas-readout-master

extra:
  recipe-maintainers:
    - g5t
